name: SKN18-4th

services:
  db:
    image: pgvector/pgvector:pg18
    container_name: pg-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-sknproject4}
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root1234}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgvector-data:/var/lib/postgresql/data
      - ../scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB:-sknproject4} -U ${POSTGRES_USER:-root}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  pgvector-data:
